name: Run Jest tests

on: [pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install
        uses: bahmutov/npm-install@v1
      - name: Fetch base branch
        run: |
          # git fetch --no-tags --depth=1 origin ${{ github.base_ref }}
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/* # fetches all branches
          git checkout -b ${{ github.base_ref }}
          git checkout ${{ github.event.pull_request.head.sha }} # checks out the SHA of the HEAD from the PR
      - name: Tests
        run: |
          yarn test --changedSince=${{ github.base_ref }}
      # - name: Main Testing
      #   uses: mattallty/jest-github-action@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     # this is just an example, this could be any command that will trigger jest
      #     test-command: "yarn test"
      #     changes-only: true
