name: Run Jest tests

on: [pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        uses: bahmutov/npm-install@v1
      - name: Fetch base branch
        run: |
          git fetch --no-tags --depth=1 origin ${{ github.base_ref }}
          git checkout -b origin/${{ github.base_ref }}
          git checkout ${{ github.event.pull_request.head.sha }}
      - name: Tests
        run: |
          yarn test --changedSince=origin/${{ github.base_ref }}
      # - name: Main Testing
      #   uses: mattallty/jest-github-action@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     # this is just an example, this could be any command that will trigger jest
      #     test-command: "yarn test"
      #     changes-only: true
