name: Run Jest tests

on: [pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        uses: borales/actions-yarn@master
        with:
          cmd: install
      - name: Main Testing
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # this is just an example, this could be any command that will trigger jest
          test-command: "yarn test"
          changes-only: true
